"""add association proxy through methods

Revision ID: a81220488c4a
Revises: 17373d7ee7b1
Create Date: 2023-06-13 13:10:36.202383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81220488c4a'
down_revision = '17373d7ee7b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
